FROM python:3.11-slim


WORKDIR /app


COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt


COPY . .


# Streamlit configuration
RUN mkdir -p /root/.streamlit && \
    printf '[server]\n\
headless=true\n\
address="0.0.0.0"\n\
port=8501\n\
enableCORS=false\n\
enableXsrfProtection=false\n\
\n\
[browser]\n\
serverAddress="castelchatx.tnpdigitallab.com"\n\
gatherUsageStats=false\n' \
> /root/.streamlit/config.toml


EXPOSE 8501


CMD ["streamlit", "run", "streamlit/app.py", "--server.address=0.0.0.0", "--server.port=8501"]